// User
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const SET_LOADING = "SET_LOADING";
export const SET_LOADING_LOCAL = "SET_LOADING_LOCAL";
export const SET_LOADING_GOOGLE = "SET_LOADING_GOOGLE";
// Dark mode
export const SET_DARK_MODE = "SET_DARK_MODE";
// Browse
export const BROWSE_HOME_LOAD = 'BROWSE_HOME_LOAD'
export const BROWSE_HOME_SUCCESS = 'BROWSE_HOME_SUCCESS'
export const BROWSE_HOME_FAIL = 'BROWSE_HOME_FAIL'
export const BROWSE_MOVIES_LOAD = 'BROWSE_MOVIES_LOAD'
export const BROWSE_MOVIES_SUCCESS = 'BROWSE_MOVIES_SUCCESS'
export const BROWSE_MOVIES_FAIL = 'BROWSE_MOVIES_FAIL'
export const BROWSE_TVSHOWS_LOAD = 'BROWSE_TVSHOWS_LOAD'
export const BROWSE_TVSHOWS_SUCCESS = 'BROWSE_TVSHOWS_SUCCESS'
export const BROWSE_TVSHOWS_FAIL = 'BROWSE_TVSHOWS_FAIL'
// Watch
export const GET_MEDIA_LOAD = 'GET_MEDIA_LOAD'
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS'
export const GET_MEDIA_FAIL = 'GET_MEDIA_FAIL'
export const HANDLE_MODAL_IS_OPEN = 'HANDLE_MODAL_IS_OPEN'
