export const HOME = '/'
export const BROWSE = '/browse'
export const SIGN_IN = '/signin'
export const SIGN_UP = '/signup'
export const MOVIES = '/browse/movies'
export const TV_SHOWS = '/browse/tvshows'
export const MY_LIST = '/browse/mylist'
export const NOT_FOUND = '/404'